# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"rand_par": "02_rec_to_ode.ipynb",
         "traj_solve": "02_rec_to_ode.ipynb",
         "traj_2_measurement": "00_traj_to_meas.ipynb"}

modules = ["traj_to_meas.py",
           "meas_to_rec.py",
           "rec_to_ode.py"]

doc_url = "https://maimanuel.github.io/sparseodes/"

git_url = "https://github.com/maimanuel/sparseodes/tree/master/"

def custom_doc_links(name): return None
